### ISSUE TITLE
Types of property 'node' are incompatible.

### ISSUE THREAD

**Issue by include** [eladb/cdk-dynamo-table-viewer#6]
Hi,

I am learning AWS-CDK  and following the cdkworkshop without issues until now. So when I reach this chapter https://cdkworkshop.com/20-typescript/50-table-viewer/300-add.html after installing cdk-dynamo-table-viewer and loading this construct, I can't get further. (I don't know TS enough to debug...)

The error code I get is:

```sh
lib/cdk-workshop-stack.ts:43:35 - error TS2345: Argument of type 'this' is not assignable to parameter of type 'Construct'.
  Type 'CdkWorkshopStack' is not assignable to type 'Construct'.
    Types of property 'node' are incompatible.
      Type 'import("/Users/include/Documents/dev/myROOT/gitlab/cookielabs/z-play/aws/cdk-workshop/node_modules/@aws-cdk/core/lib/construct").ConstructNode' is not assignable to type 'import("/Users/include/Documents/dev/myROOT/gitlab/cookielabs/z-play/aws/cdk-workshop/node_modules/cdk-dynamo-table-viewer/node_modules/@aws-cdk/core/lib/construct").ConstructNode'.
        Types have separate declarations of a private property 'host'.

43         const v = new TableViewer(this, 'ViewHitCounter', {
                                     ~~~~

[10:48:17 PM] Found 1 error. Watching for file changes.
```

I've reviewed my code 3x to check if I had some typo or something :) but I think nop.

Can you please check this. Thank you very much.

PS: I am using your latest version. 3.0.3

Cheers,
Francisco

**Comment by eladb** [comment]
Thanks for reporting. This is because the table viewer was still targeting the pre 1.0 CDK so there was a mismatch in versions. I've upgraded the table viewer and it should be published within an hour. Nuke your node_modules and make sure cdk-dynamo-table-viewer is 3.0.4

**Comment by include** [comment]
many thanks :) 🙏

**Comment by jpcaparas** [comment]
If you are coming from the [CDK Workshop guide](https://cdkworkshop.com/20-typescript/50-table-viewer/200-install.html), simply run:

```
npm install cdk-dynamo-table-viewer@3.0.4
```

The tag versions are really weird though

**Comment by jpcaparas** [comment]
Actually, if you are getting:

```
 "The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs
14.x) while creating or updating functions.
```

It's better to install the 3.1 version instead:

```
npm install cdk-dynamo-table-viewer@3.1
```

As the Node.js runtime version was bumped to v12
